browser=chrome
baseUrl=https://biz.test.paytmcheckout.com
qrCodeUrl=https://test-assets.test.paytmcheckout.com/qtukgscdk72p5mn44g0qusq2da7y
implicitWait=10
explicitWait=30
deviceWidth=477
deviceHeight=785
catalogApiBaseUrl=https://biz.test.paytmcheckout.com
catalogApiPath=/qr_online_order/
qrScanCode=eLzWyast1V
headless=false